# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
