# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170829_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='localurl',
            field=models.CharField(max_length=255, verbose_name='Viewer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
