# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20171219_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.SmallIntegerField(choices=[(0, b'unknow'), (1, b'aborted'), (7, b'cancelled'), (2, b'waiting'), (8, b'scheduled'), (6, b'new'), (3, b'warn'), (3, b'warning'), (4, b'fail'), (5, b'pass'), (9, b'panic'), (10, b'failinstall'), (11, b'skip')], db_index=True, default=0),
        ),
    ]
