# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 13:52
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    Recipe = apps.get_model("core", "Recipe")

    for it in Task.objects.exclude(uid__startswith="T:"):
        it.uid = "T:%d" % int(it.uid)
        it.save()

    for it in Recipe.objects.exclude(uid__startswith="R:"):
        it.uid = "R:%d" % int(it.uid)
        it.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180124_1150'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
